# -*- coding: utf-8 -*-
"""Netflix stock analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TR_I55YvaWRyQER9DT7XxLVKrUp7A6R9

Netflix Stock analysis
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
# %matplotlib inline
import plotly.express as px
import plotly.graph_objects as go

from datetime import datetime
from datetime import date
from datetime import timedelta

data= pd.read_csv('NFLX.csv')

data.head()

# Filtering out the ticker row identifier ('NFLX') so we only have numbers left
data = data[data['open'] != 'NFLX']



# Volume of Stock traded

sns.set(rc={'figure.figsize': (10,5)})

import importlib
importlib.reload(plt)
plt.clf()
plt.close("all")

if "date" in data.index.names:
    data.reset_index(inplace=True)

data["volume"] = pd.to_numeric(data["volume"], errors="coerce")
data["date"] = pd.to_datetime(data["date"])

data = data.sort_values(by="date", ascending=True)

data.set_index("date", inplace=True)

sns.lineplot(x=data.index, y=data["volume"], label="volume")
plt.title("Netflix Stock Volume")
plt.xlabel("Date")
plt.ylabel("Volume")
plt.show()

numeric_cols = ['open', 'high', 'low', 'close', 'adj_close']
for col in numeric_cols:
    data[col] = pd.to_numeric(data[col], errors='coerce')

data.dropna(subset=numeric_cols, inplace=True)

data.plot(y=['high', 'close', 'open' ], title= 'Netflix stock price in terms with high close and open')

fig, (ax1,ax2,ax3)= plt.subplots(3, figsize=(15,15))
data.groupby(data.index.day).mean().plot(y='volume', ax=ax1, xlabel='Day', ylabel='volume')
data.groupby(data.index.month).mean().plot(y='volume', ax=ax2, xlabel='Month', ylabel='volume')
data.groupby(data.index.year).mean().plot(y='volume', ax=ax3, xlabel='Year', ylabel='volume')

# Top 5 date with highest stock price

a= data.sort_values(by= 'high', ascending= False)
a.head()

# # Top 5 date with lowest stock price

b= data.sort_values(by= 'low', ascending= True)
b.head()

# Creating graph for high and low stock

from matplotlib import axes
fig,axes= plt.subplots(nrows=1, ncols=2, figsize=(15,5))
fig.suptitle('High and Low Stock')

#plot
sns.lineplot(ax=axes[0], x=data.index, y=data['high'], label='high')
sns.lineplot(ax=axes[1], x=data.index, y=data['low'], label='low')

# Calculating smooth trend lines over 50-day and 200-day windows

data['SMA_50'] = data['adj_close'].rolling(window=50).mean()
data['SMA_200'] = data['adj_close'].rolling(window=200).mean()

fig, (ax1,ax2,ax3) = plt.subplots(3, 1, figsize=(14, 10))

ax1.plot(data.index, data['adj_close'], label='Daily Adjusted Close Price', color='royalblue', alpha=0.5)
ax1.set_title('Daily Adjusted Close Price')
ax1.legend()

ax2.plot(data.index, data['SMA_50'], label='50-Day Trend (Short-Term)', color='darkorange')
ax2.set_title('50-Day Simple Moving Average')
ax2.legend()

ax3.plot(data.index, data['SMA_200'], label='200-Day Trend (Long-Term)', color='crimson')
ax3.set_title('200-Day Simple Moving Average')
ax3.legend()

fig.tight_layout() # Adjust layout to prevent overlap
plt.show()

# Calculate the percentage change from day to day to measure volatility
data['Daily_Return'] = data['adj_close'].pct_change()

plt.figure(figsize=(10, 5))
sns.histplot(data['Daily_Return'].dropna(), bins=100, kde=True, color='purple')
plt.title('Distribution of Netflix Daily Returns (Risk)', fontsize=14, fontweight='bold')
plt.xlabel('Daily Return (Decimal format: e.g., 0.02 = +2%)')
plt.ylabel('Number of Days')
plt.axvline(x=0, color='black', linestyle='--')
plt.show()

# ==========================================
# STEP 4: CUMULATIVE RETURNS (COMPOUND GROWTH)
# ==========================================

# Compound the daily returns to track how a single $1 investment grows over time
data['Cumulative_Return'] = (1 + data['Daily_Return'].dropna()).cumprod()

# Plot long-term compounded growth on a logarithmic scale
plt.figure(figsize=(14, 6))
plt.plot(data.index, data['Cumulative_Return'], color='seagreen')
plt.yscale('log')
plt.title('Growth of a $1 Investment in Netflix Over Time', fontsize=14, fontweight='bold')
plt.xlabel('Date')
plt.ylabel('Value of Investment ($)')
plt.show()

"""  Executive Analysis Report: Netflix (NFLX) Historical Stock Performance & Market Risk

  1. Project Overview & Operational Setup
  This analysis delivers an end-to-end evaluation of Netflix Inc. (NFLX) historical equity data spanning from its initial public offering in 2002 through recent trading periods. The objective is to decode structural long-term growth trends, quantify short-term price momentum, examine architectural volume distribution shifts, and map the statistical risk profile of daily asset returns.

The underlying data cleaning pipeline successfully isolates target transactional rows, addresses programmatic type-casting constraints (transforming historical text-based financial indices into functional float64 and int64 metrics), and establishes a strict datetime timeline baseline for time-series indexing.

2. Micro & Macro Volume Diagnostics
Evaluating baseline share-volume activity across distinct dimensional constraints (Daily, Monthly, and Annual aggregates) reveals several key operational behaviors:

Micro-Scale Behavior (Day & Month): Aggregated day-of-the-month and monthly metrics demonstrate balanced baseline ranges, suggesting that typical institutional rebalancing, option expirations, or retail inflows distribute evenly across routine calendar cycles without causing systemic transactional bottlenecks.

Macro-Scale Growth (Annual Trend): Long-term volume metrics map the massive transition of Netflix from an early-stage DVD rental disruptor into a dominant global streaming media conglomerate. Structural spikes in historical annual volumes correspond precisely with major market milestones, high-volatility broader market shifts, and shifts in subscriber acquisition curves.

3. Price Trajectory & Trend Identifiers
By evaluating the raw asset price against 50-Day (Short-Term) and 200-Day (Long-Term) Simple Moving Averages (SMA), we smooth out volatile daily price variations to reveal structural momentum:

Structural Health: Throughout its historical timeline, prolonged intervals where the daily closing price sustained a position above the 200-day moving average confirm extended macroeconomic bull markets.

Momentum Shifts: Intersections between the 50-day and 200-day trend lines act as critical momentum indicators, tracking historical transitions between aggressive equity accumulation phases and broader macroeconomic corrections.

4. Risk Profile & Volatility Analysis (Returns Distribution)
Transitioning from nominal stock values to daily percentage adjustments allows for a precise evaluation of investor risk:Central Tendency & Stability: The daily returns histogram reveals an exceptionally tall, concentrated, symmetric distribution tower tightly clustered around the $0\%$ baseline. This mathematical behavior establishes that on a typical trading day, Netflix’s pricing variance remains minimal, steady, and functionally balanced without systemic pressure toward extreme daily swings.Leptokurtic Risk (Fat Tails): While routine days are highly stable, the distribution features extensive horizontal boundaries (Tails). Because historical daily shocks—such as sudden earnings adjustments or global subscriber revisions—can spark extreme historical sessions, these rare outliers sit at the edges of the timeline. They represent critical asymmetric risk factors that standard rolling averages understate.

5. Compounded Growth Valuation
Compounding daily percentage shifts sequentially through a cumulative product metric tracks the structural performance of capital over time. Observed via a logarithmic scale to account for massive exponential expansion, the metric outlines the sheer scale of Netflix’s market trajectory. It illustrates how micro percentage gains compound over long horizons into extraordinary enterprise value, demonstrating the massive wealth-generation capacity driven by long-term paradigm shifts in global entertainment consumption.

"""